/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as RiskAnalysisRouteImport } from './routes/risk-analysis'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ChangeManagementRouteImport } from './routes/change-management'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAnalysisRoute = RiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeManagementRoute = ChangeManagementRouteImport.update({
  id: '/change-management',
  path: '/change-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/change-management': typeof ChangeManagementRoute
  '/evaluation': typeof EvaluationRoute
  '/projects': typeof ProjectsRoute
  '/results': typeof ResultsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/simulation': typeof SimulationRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/change-management': typeof ChangeManagementRoute
  '/evaluation': typeof EvaluationRoute
  '/projects': typeof ProjectsRoute
  '/results': typeof ResultsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/simulation': typeof SimulationRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/change-management': typeof ChangeManagementRoute
  '/evaluation': typeof EvaluationRoute
  '/projects': typeof ProjectsRoute
  '/results': typeof ResultsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
  '/simulation': typeof SimulationRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/change-management'
    | '/evaluation'
    | '/projects'
    | '/results'
    | '/risk-analysis'
    | '/simulation'
    | '/strategy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/change-management'
    | '/evaluation'
    | '/projects'
    | '/results'
    | '/risk-analysis'
    | '/simulation'
    | '/strategy'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/change-management'
    | '/evaluation'
    | '/projects'
    | '/results'
    | '/risk-analysis'
    | '/simulation'
    | '/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ChangeManagementRoute: typeof ChangeManagementRoute
  EvaluationRoute: typeof EvaluationRoute
  ProjectsRoute: typeof ProjectsRoute
  ResultsRoute: typeof ResultsRoute
  RiskAnalysisRoute: typeof RiskAnalysisRoute
  SimulationRoute: typeof SimulationRoute
  StrategyRoute: typeof StrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-analysis': {
      id: '/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof RiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-management': {
      id: '/change-management'
      path: '/change-management'
      fullPath: '/change-management'
      preLoaderRoute: typeof ChangeManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ChangeManagementRoute: ChangeManagementRoute,
  EvaluationRoute: EvaluationRoute,
  ProjectsRoute: ProjectsRoute,
  ResultsRoute: ResultsRoute,
  RiskAnalysisRoute: RiskAnalysisRoute,
  SimulationRoute: SimulationRoute,
  StrategyRoute: StrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
